### ISSUE TITLE
Procedures de delete

### ISSUE THREAD

**Issue by lurifn** [AllSoft-br/BD_Avros#1]
Criar procedures que deletem registros do banco de dados
@WallaceOl 

O sistema está fazendo delete de relações entre menor e representante, atualmente

**Comment by WallaceOl** [comment]
Tabom. o/

De: Luana Nascimento [mailto:notifications@github.com] 
Enviada em: terça-feira, 5 de maio de 2015 13:31
Para: AllSoft-br/BD_Avros
Cc: WallaceOl
Assunto: [BD_Avros] Procedures de delete (#1)

Criar procedures que deletem registros do banco de dados
@WallaceOl https://github.com/WallaceOl  

O sistema está fazendo delete de relações entre menor e representante, atualmente

**Comment by lurifn** [comment]
falta delete de cliente .-.

**Comment by WallaceOl** [comment]
Luana, te amo <3
